# 1.np.sort

In [1]:
# Return a sorted copy of an array..

import numpy as np
 
    # 1D
a= np.random.randint(1,100,15)
print(a)

np.sort(a)

[ 6 14 33 66 89 37 93 18 90 11 39 82 11 11 26]


array([ 6, 11, 11, 11, 14, 18, 26, 33, 37, 39, 66, 82, 89, 90, 93])

In [2]:
# 2D
b= np.random.randint(1,100,24).reshape(6,4)
print(b)

print(np.sort(b))  # sort row vise..
print(np.sort(b,axis=0))   # sort column vise

[[16 36 61 48]
 [74 96 42 42]
 [ 7  6 96 43]
 [95 79 70 38]
 [34  1 69  3]
 [57 86 99 65]]
[[16 36 48 61]
 [42 42 74 96]
 [ 6  7 43 96]
 [38 70 79 95]
 [ 1  3 34 69]
 [57 65 86 99]]
[[ 7  1 42  3]
 [16  6 61 38]
 [34 36 69 42]
 [57 79 70 43]
 [74 86 96 48]
 [95 96 99 65]]


# 2.np.append:

In [ ]:
# The numpy.append() values along the mentioned axis at the end of the array.

In [3]:
print(a)
print(np.append(a,200))

[ 6 14 33 66 89 37 93 18 90 11 39 82 11 11 26]
[  6  14  33  66  89  37  93  18  90  11  39  82  11  11  26 200]


In [6]:
# 2D
print(b)
print(np.append(b,np.ones((b.shape[0],1)),axis=1))  # add new column
# print(np.append(b,np.random.random((b.shape[0],1)),axis=1))  # we also add random item...

[[16 36 61 48]
 [74 96 42 42]
 [ 7  6 96 43]
 [95 79 70 38]
 [34  1 69  3]
 [57 86 99 65]]
[[16. 36. 61. 48.  1.]
 [74. 96. 42. 42.  1.]
 [ 7.  6. 96. 43.  1.]
 [95. 79. 70. 38.  1.]
 [34.  1. 69.  3.  1.]
 [57. 86. 99. 65.  1.]]


# 3.np.concatenate:

In [24]:
# numpy.concatenate() func concatenate a sequence of array along an existing axis..

c= np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)
print(c)
print(d)

# we want to concatenate both c,d..
print(np.concatenate((c,d),axis=0))   # concatenate in column
print(np.concatenate((c,d),axis=1))   # concatenate in row


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


# 4.np.unique:

In [26]:
# with the help of np.unique() method,we can get the unique values from an array given as parameter in np.unique() method.

e= np.array([1,1,2,2,3,3,4,4,5,5,6,6,7,7])
print(e)
print(np.unique(e))  # to get unique items...

[1 1 2 2 3 3 4 4 5 5 6 6 7 7]
[1 2 3 4 5 6 7]


# 5.np.expand_dims

In [40]:
# with the help of expan_dims() method, we can get the expanded dimensions of an array.

print(a)
#print(a.shape)
print(np.expand_dims(a,axis=0))  # it convert 1D into 2D, 2D into 3D and so on...
#print(np.expand_dims(a,axis=0).shape) # check shape...
print(np.expand_dims(a,axis=1))
#print(np.expand_dims(a,axis=1).shape)

[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]
[[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]]
[[13]
 [28]
 [98]
 [84]
 [60]
 [97]
 [11]
 [87]
 [40]
 [63]
 [79]
 [75]
 [61]
 [36]
 [33]]


# 6.np.where:

In [47]:
# The np.where() func return the indices of elements in an input array where the given condition is satisfied.

print(a)

print(np.where(a>50))  # find all indices with value greater than 50..

[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]
(array([ 2,  3,  4,  5,  7,  9, 10, 11, 12], dtype=int64),)


In [88]:
# replace all values greater than 50 with 0:

#np.where(condition,True,False)  # syntax..

np.where(a>50,0,a)

array([ 0,  0,  0,  0,  0,  0, 11,  0, 40,  0,  0,  0,  0, 36, 33])

In [49]:
# replace all even number with 0:
np.where(a%2==0,0,a)

array([13,  0,  0,  0,  0, 97, 11, 87,  0, 63, 79, 75, 61,  0, 33])

# 7.np.argmax:

In [51]:
# np.argmas() return indices of the max element of the array in a particular axis.

print(a)
print(np.argmax(a))

[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]
2


In [55]:
#2D
print(b)
np.argmax(b,axis=0) # it tells indices of max element in column ..

[[28 86  4 92]
 [77 69 10  9]
 [58 91 32 70]
 [79 71 42 21]
 [25 92 81 12]
 [14 17 63 84]]


array([3, 4, 4, 0], dtype=int64)

# 8.np.argmin:

In [56]:
# tell min element indices...
print(a)
print(np.argmin(a))

[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]
6


# 9.np.cumsum:

In [57]:
# np.cumsum()is used when we want to compute the cumpulative sum of array elements over a given axis.
# cumpulative sum means( like babar runs in 1st inning is 19 and  then in 2nd is 24, now the  sum of all 
# carier runs of babar iks is cumpulative sum..   )

print(a)
print(np.cumsum(a))

[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]
[ 13  41 139 223 283 380 391 478 518 581 660 735 796 832 865]


In [58]:
# 2D

print(b)
print(np.cumsum(b,axis=0))  # 0 means col, 1 means row..

[[28 86  4 92]
 [77 69 10  9]
 [58 91 32 70]
 [79 71 42 21]
 [25 92 81 12]
 [14 17 63 84]]
[[ 28  86   4  92]
 [105 155  14 101]
 [163 246  46 171]
 [242 317  88 192]
 [267 409 169 204]
 [281 426 232 288]]


# 10.np.cumprod:

In [60]:
# it's like cumsum() func but it perform multiplication not addition..
print(a)
print(np.cumprod(a))

[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]
[         13         364       35672     2996448   179786880   259458176
 -1440927360  -806628736  2094588928 -1184883712   883467264  1835535360
   298507264 -2138640384 -1855655936]


# 11.np.percentile:

In [62]:
# np.percentile() used to compute the nth percentile of the given data(array element) along the specidied axis..
# check what percentile is ???
print(a)
print(np.percentile(a,100))  # 100 mean max
print(np.percentile(a,0))    # min
print(np.percentile(a,50))   # tell median

[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]
98.0
11.0
61.0


# 12.np.histogram:

In [65]:
# numpy has a built-in func np.histogram which reresent the frequency of the data distribution in graphical form..

print(a)
print(np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])) 

# it tell how much numbers in bins, e.g 0 se 10 ma ketny number ha,then 10 se 20, and so on....

[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]
(array([0, 2, 1, 2, 1, 0, 3, 2, 2, 2], dtype=int64), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


# 13.np.corrcoef:


In [66]:
# return pearson product moment correiation coefficients..
# check correiation coefficients ???

salary= np.array([20000,40000,25000,35000,60000])
experiance=np.array([1,3,2,4,2])

np.corrcoef(salary,experiance)


array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# 14.np.isin:

In [94]:
# with the help of isin(), we can see that one array having values are checked in a diff numpy array having
# diff elements with diff sizes...
# or
# it help us to find multiple items..

print(a)
item=[10,20,30,40,60,70,80,98]
print(np.isin(a,item))

[110 500  98  84  60  97  11  87  40  63  79  75  61  36  33]
[False False  True False  True False False False  True False False False
 False False False]


# 15.np.flip:

In [69]:
# np.flip() reverse the order of array elements along the specifies axis, preserving the shape of the array...
# simply it reverse the elements..
print(a)
print(np.flip(a))

[13 28 98 84 60 97 11 87 40 63 79 75 61 36 33]
[33 36 61 75 79 63 40 87 11 97 60 84 98 28 13]


In [70]:
# 2D:
print(b)
print(np.flip(b,axis=0)) # reverse column..

[[28 86  4 92]
 [77 69 10  9]
 [58 91 32 70]
 [79 71 42 21]
 [25 92 81 12]
 [14 17 63 84]]
[[14 17 63 84]
 [25 92 81 12]
 [79 71 42 21]
 [58 91 32 70]
 [77 69 10  9]
 [28 86  4 92]]


# 16.np.put:

In [72]:
# The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed 
# works on flattened array...
# put is for putting new items  on existing place..
print(a)
print(np.put(a,[0,1],[110,500])) # the change is permanantly..
a

[110 500  98  84  60  97  11  87  40  63  79  75  61  36  33]
None


array([110, 500,  98,  84,  60,  97,  11,  87,  40,  63,  79,  75,  61,
        36,  33])

# 17.np.delete:

In [74]:
# The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

print(a)
print(np.delete(a,0))  # tell indices to delete items...
print(np.delete(a,[1,2,3,4]))  # multiple item deletion..

[110 500  98  84  60  97  11  87  40  63  79  75  61  36  33]
[500  98  84  60  97  11  87  40  63  79  75  61  36  33]
[110  97  11  87  40  63  79  75  61  36  33]


# Set Functions:

1.np.union1d          
2.np.intersect1d          
3.np.setdiff1d        
4.np.setxor1d        
5.np.in1d       

In [83]:
m= np.array([1,2,3,4,5])
n= np.array([3,4,5,6,7])


print(np.union1d(m,n))  # it calculate union..

print(np.intersect1d(m,n))  # tell intersection..


#setdiff1d() function find the set difference of two arrays and return the unique values in arr1 that are not in arr2..
print(np.setdiff1d(m,n)) 


# setxor1d() function find the set exclusive-or of two arrays and return the sorted, unique values that are in
# only one (not both) of the input arrays.
print(np.setxor1d(m,n)) 


# in1d() function test whether each element of a 1-D array is also present in a second array and return a
# boolean array the same length as arr1 that is True where an element of arr1 is in arr2 and False otherwise.
print(np.in1d(m,1))

[1 2 3 4 5 6 7]
[3 4 5]
[1 2]
[1 2 6 7]
[ True False False False False]


# np.clip:

In [86]:
#clip() function is used to Clip (limit) the values in an array...


print(a)

print(np.clip(a,a_min=30,a_max=70))

[110 500  98  84  60  97  11  87  40  63  79  75  61  36  33]
[70 70 70 70 60 70 30 70 40 63 70 70 61 36 33]


# np.maximum:

In [7]:
# maximum() function is used to find the element-wise maximum of array elements. 

import numpy as np
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

np.maximum(a,b)


array([6, 3, 1, 7, 8])