# Numpy:

In [ ]:
# Numpy is the fundamental package for scienttific computing in python. it is a python library that provides 
# a multidimensional array object, various derived object(such as masked array and matrices), and an assortment 
# of routines for last opeartions on arrays,including mathematical,logical,shape manipulation,sorting,selecting,I/O,
# discrete fourier transforms,b asic linear algebra,basic statistical operations, random simulation and much more.


# At the core of the numpy package, is the ndarray object. This encapsolates n-dimensional arrays of homogenous data types.

Numpy Arrays vs python sequences:

In [ ]:
#1- Numpy arrays have a fixed size at creation,unlike python lists(which can grow dynamically). Changing the size of 
# an ndarray will creat a new array and delete the original.

#2- The elements in a numpy array are all required to be of the same data type, and thus will be the same size in memory.

#3- Numpy arrays facilitate advanced mathematical and other types of opeartions on large number of data. Typically such
# operations are executed more efficiently and with less code than is possible using python's built-in sequences.

#4- A growing plethora of scientific and mathematical python-based packages are using numPy arrays; through these typically
# support python sequence input, they convert such input to numPy arrays prior to processing, and they often output numPy
# arrays

Creating NmPy arrays:

In [2]:
# "np.array" is a basic function. we can creat array by using "np.array".... 

import numpy as np

a = np.array([1,2,3])   # like vector
print(a)  # this is numpy array...1D


print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
# 2D

b= np.array([[1,2,3],[3,4,5]])   # like matrix..2D
print(b)

[[1 2 3]
 [3 4 5]]


In [8]:
# 3D

c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])   # like tencer..
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


data-type array:

In [3]:

print(np.array([1,2,3],dtype=float))  # list into float...

print(np.array([1,2,3],dtype=bool))

print(np.array([1,2,3],dtype=complex))

print(np.array([1,2,3],dtype=int))

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]
[1 2 3]


"np.arange"

In [5]:
# there is another func "np.arange". we can also creat array by using this func...
# it's like range() function in python...

np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

reshape

In [6]:
# with "np.arange" func we also use "reshape" func..

# it convert a given numpy array into another shape....

print(np.arange(1,11).reshape(2,5)) # it creat 2 rows and 5 columns...

print(np.arange(1,13).reshape(4,3))  # it creat 4 rows and 3 col..

#etc...

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


np.ones and np.zeros:

In [18]:
# by using "np.ones" we can creat array that have all items are "1"..


print(np.ones((3,4)))    # in "np.ones" we can provide tuple with shape...


# one more func "np.zeros" same like "np.ones", it print "0"
print(np.zeros((3,4)))




# where we use these two func???
# we use this functions to quickly initialize "1" or "0"...



# there are three func to initialize arrays.. "np.ones" , "np.zeros" , "np.random"..

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


"np.random"

In [40]:
# we use random to creat random numbers....
a= np.random.random((3,4))


# there are three func to initialize arrays.. "np.ones" , "np.zeros" , "np.random"..

"np.linspace"

In [4]:
# it's full form is "linear space"...
#  it creats sequence of evenly spaced values within a defined intervel ...

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

"np.identity"

In [7]:
# we can creat identity matrics by using "np.identity"..

np.identity(3)



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

tile:

In [21]:
# NumPy tile() function in Python is used to construct an array by repeating a given input array by
# specified number of times given by the reps parameter.
a= np.array([1,2,3])
print(a)
np.tile(a,6)




[1 2 3]


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# Array attributes:

In [22]:
a1= np.arange(10)
a2= np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)



"ndim"

In [17]:
# "number of dimensions", by using this func we can find dimension...(dimension means 1d, 2D, 3D)

a3.ndim

3

shape

In [20]:
# this func tell how many items in dimensions..

a3.shape


(2, 2, 2)

size

In [22]:
# it tells no. of items..
a2.size


12

"itemsize"

In [24]:
# it tell how much memory occupies by each item..

a3.itemsize

4

"dtype"

In [27]:
# it tells data-type of items..

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing data-types:

In [ ]:
# we can change the data-type of any numpy...

"astype"

In [36]:
# by using this we can change data-type, like int32 into int64 or 64 into 32...
# agr zyada memory ocuupie kr rha ha tu by using this, hum kum memory ocucupie krwa skty ha...


print(a3.dtype)

a3.astype(np.int64)



int32


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array operations:

In [10]:
# we can run many mathematical operations on numpy arrays..

a1= np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(4,3)
a2



array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
# There are two types of operations:

# 1-Scaler operation
# 2-vector operations

In [49]:
# 1-Scaler operation:

# airthematic operators..

a1 + 2   # all airthematic operators works..

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [52]:
# relational operators...
print(a2==15)
print(a2>5)
print(a2<5)

[[False False False  True]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [54]:
# 2-vector operations: works on two numpy arrays..

# airthematic..

a1+a2
a1*a2         # all airthematic operators works..

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Arrays Functions:

In [37]:
a1= np.random.random((3,3))
a1= np.round(a1*100)  # round use to roundoff the items..
a1

array([[33., 56., 52.],
       [46., 49., 79.],
       [15., 91., 90.]])

In [41]:
# max  : it tells max n umber in matrics...
print(a1)
print("Max: ",np.max(a1))

#min
print('Min: ',np.min(a1))

# sum
print('Sum: ',np.sum(a1))

# product: give mulitplications...
print('Product: ',np.prod(a1))

[[33. 56. 52.]
 [46. 49. 79.]
 [15. 91. 90.]]
Max:  91.0
Min:  15.0
Sum:  511.0
Product:  2102139216777600.0


In [43]:
# we can also fetch items:

print(a1)
# 0 means column, 1 mean row
np.sum(a1,axis=1)  # min, max, sum, product all works....


[[33. 56. 52.]
 [46. 49. 79.]
 [15. 91. 90.]]


array([141., 174., 196.])

In [33]:
# mean: it calculate mean of all matrics...
# we can also calculate mean column vise or row vise...
print('Mean: ',np.mean(a1))

# median: tells the median item
print('Median: ',np.median(a1))


# standerd daviation:
print('Standered Daviation: ',np.std(a1))

#variance:
print('Variance: ',np.var(a1))

Mean:  53.44444444444444
Median:  65.0
Standered Daviation:  22.657405515445895
Variance:  513.3580246913581


In [70]:
# trignomatric functions:

np.sin(a1)  # cos, tan all works..

array([[-0.13235175,  0.01770193, -0.99920683],
       [ 0.84147098,  0.68326171,  0.55142668],
       [-0.28790332, -0.62988799, -0.15862267]])

In [73]:
# dot product: multiplay matrics...


a2= np.arange(12).reshape(3,4)
a3= np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [76]:
# log: calculate log of each item..
np.log(a1)

#exponents:
np.exp(a1)

array([[7.20048993e+10, 1.28516001e+19, 9.88903032e+42],
       [2.71828183e+00, 1.81123908e+41, 7.89629602e+13],
       [8.88611052e+06, 1.50609731e+35, 6.39843494e+17]])

In [45]:
# round: roundoff
np.round(np.random.random((2,3))*100)


# floor: peechy waly integer pr ly kr jay ga,,like 3.9 ha tu 3...
np.floor(np.random.random((2,3))*100)

# ceil: aagy waly integer pr ly kr jata ha.
np.ceil(np.random.random((2,3))*100)


array([[50., 78., 54.],
       [22., 29., 69.]])

# indexing & slicing:

In [5]:
a1= np.arange(10)
a2= np.arange(12).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)


In [6]:
# positive 7 nagetive indexing:

#1D
print(a1)
a1[0]
a1[-1]



[0 1 2 3 4 5 6 7 8 9]


9

In [7]:
# 2D indexing:
print(a2) # we need to find 6..

# 1st tell row and then tell col..three row in a2 "0,1,2"
a2[1,2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


6

In [98]:
# 3D indexing:
print(a3)  # find 5..
# in a3 there is two  2D in 3D "0,1", so 1st tell kis 2D ma number ha 5 1st 2D ma ha, and then tell row and then col...
print(a3[1,0,1])  # find 5
print(a3[0,1,1]) # find 3
print(a3[0,0,0]) # find 0

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
3
0


Slicing:

In [101]:
# 1D
print(a1)
a1[2:5]

[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4])

In [9]:
# 2D
print(a2)

print(a2[0,:])  #1st tell row and then col...we need all col so we use ":"..

print(a2[:,2])    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]


In [26]:
# 2D
print(a2)
print()
print(a2[1:,1:3])   # 5,6,9,10
print()
print(a2[0::2,0::3])   # 0,3,8,11
print()
print(a2[0::2,1::2])  # 1,3,9,11
print()
print(a2[1,0::3])  # 4,7
print()
print(a2[0:2,1:])    # 1,2,3,5,6,7
print()
print(a2[1:,0::2])   # 4,6,8,10

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 5  6]
 [ 9 10]]

[[ 0  3]
 [ 8 11]]

[[ 1  3]
 [ 9 11]]

[4 7]

[[1 2 3]
 [5 6 7]]

[[ 4  6]
 [ 8 10]]


In [46]:
# 3D
a3= np.arange(27).reshape(3,3,3)
print(a3)
print("*************************")

#print(a3[1,1,:])   # bech waly ka 2nd row
print()
#print(a3[2,1:,1::])   # 22,23,25,26
print()
print(a3[::2,0::3,0::2])   # 0,2,18,20
print()
print(a3[::2,2::2,0::2])       # 6,8,21,23

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
*************************


[[[ 0  2]]

 [[18 20]]]

[[[ 6  8]]

 [[24 26]]]


# Itrating:

In [168]:
print(a1)
for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [169]:
#2D
print(a2)

for i in a2:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [170]:
print(a3)
print("**********")

for i in a3:
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
**********
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [171]:
# if you want to print individual loop,, use "np.nditer"..

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping:

In [ ]:
# reshape: already done...

Transpose

In [174]:
# it works like transpose that we read in matrix in 11th...

print(a2)
print("****************")
print(np.transpose(a2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
****************
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [175]:
# transpose has one more syntax...
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

ravel

In [178]:
# it convert dimensions into 1D dimension. dimensions maybe 2D or 3D or so on..

print(a2)

print(a2.ravel())

print("*******************")

print(a3)
print(a3.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
*******************
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


# Stacking:

In [ ]:
# Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be stacked.

In [4]:

a4= np.arange(12).reshape(3,4)
a5= np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [182]:
# horizontal stacking:

np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [5]:
# vertical stacking:
print(a4)
print(a5)
np.vstack((a4,a5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting

In [ ]:
#Splitting is reverse operation of stacking.



In [36]:
# horizantal spliting:
print(a4)

np.hsplit(a4,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [188]:
# vertical spliting:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]